# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a the fixed parameter
#' @param b the fixed parameter
#' @param N the fixed parameter
#' @return a chain with tagret joint density \code{x}
#' @examples
#' \dontrun{
#' a<-1
#' b<-1
#' N<-10000
#' X1<-fun98(a,b,N)
#' plot(X1[,1],X1[,2],xlab = "x",ylab = "y")
#' }
#' @export
fun98 <- function(a, b, N) {
    .Call('_StatComp21056_fun98', PACKAGE = 'StatComp21056', a, b, N)
}

